<?php 
	function dravInteresting()
	{
		echo "
			<div id='zanim'>
				<img src='slike/pozadinaZaReg2.jpg' alt='slika se nemoze prikazati' height='698' width='998'>
		
				<div id='zan1'>
					<p id='naslovZ'> Zanimljivosti iz sveta automobila </p>
					<ul id='tabelaZanimljivosti'>
						<li>AMS predstavio elektroautomobil - skoro 10 puta štedljiviji <a href='http://www.novosti.rs/vesti/naslovna/auto/aktuelno.233.html:501513-AMS-predstavio-elektroautomobil---skoro-10-puta-stedljiviji'>više o ovoj vesti</a></li>
						<li>Folksvagen kupuje Fijat? <a href='http://www.novosti.rs/vesti/naslovna/auto/aktuelno.233.html:501310-Folksvagen-kupuje-Fijat'>više o ovoj vesti</a></li>
						<li>Sasvim nova „korsa“ <a href='http://www.novosti.rs/vesti/naslovna/auto/aktuelno.233.html:501964-Sasvim-nova-korsa'>više o ovoj vesti</a></li>
						<li>Atraktivan i ekonomičan C4 <a href='http://www.novosti.rs/vesti/naslovna/auto/aktuelno.233.html:500924-Atraktivan-i-ekonomican-C4'>više o ovoj vesti</a></li>
						<li>Honda povlači 175.000 hibridnih vozila<a href='http://www.novosti.rs/vesti/naslovna/auto/aktuelno.233.html:500234-Honda-povlaci-175000-hibridnih-vozila'>više o ovoj vesti</a></li>

					</ul>
					<div id='pobednickiVideo'>
						Poštovani korisnici sajta autooglasi.rs, vaše zanimljive video klipove iz  sveta automobila možete slati našoj redakciji a svake nedelje najbolji će biti objavljeni ovde a korisnika koji nam pošalje pobednički video očekuje nagrada po izboru sponzora nagradne igre koja se iz nedelje u nedelju menja. Puno sreće u nagradnoj igri!
						<div id='poravnajJustify'>
							<span id='vecaSlova'>
								Pobednički video za ovu nedelju <br/>
							</span>

							<video width='340' height='170'  controls>
	  							<source src='video/volkswagen.mp4' type='video/mp4'>
	 							Vaš browser ne podržava video tag.
							</video>
						</div>
					</div>
				</div>


				<div class = 'logoZnaci'>
					 <a href='http://www.vw-club.rs/forum/'> <img src='slike/logovw.jpg' alt='volkswagen' class='logo'/> </a>
					 <a href='http://www.bmwclubserbia.com/forum/index.php?act=idx'> <img src='slike/logobmw.jpg' alt='volkswagen' class='logo'/> </a>
					 <a href='http://audiclubserbia.com/forum/'> <img src='slike/logoaud.jpg' alt='volkswagen' class='logo'/> </a>
					 <a href='http://www.chevroletforumserbia.com/'> <img src='slike/logoche.jpg' alt='volkswagen' class='logo'/> </a>
					 <a href='http://arcs.org.rs/forum/'> <img src='slike/logoar.jpg' alt='volkswagen' class='logo'/> </a>
					 <a href='http://www.cadillacforums.com/'> <img src='slike/logocad.jpg' alt='volkswagen' class='logo'/></a>
					 <a href='http://www.jaguarforums.com/forum/'><img src='slike/logojag.jpg' alt='volkswagen' class='logo'/></a>
					 <a href='http://www.mazdaclub.rs/forum/'><img src='slike/logoma.jpg' alt='volkswagen' class='logo'/></a>
					 <a href='http://forumsrbija.toyotaadria.com/'><img src='slike/logotoy.jpg' alt='volkswagen' class='logo'/></a>
					 <a href='http://dodgeforum.com/'><img src='slike/logodod.jpg' alt='volkswagen' class='logo'/></a>
					 <a href='http://www.fordclubserbia.org/forum/viewforum.php?f=3'><img src='slike/logoford.jpg' alt='volkswagen' class='logo'/></a>
					 <a href='http://porsche.freeforums.net/'><img src='slike/logoporshe.jpg' alt='volkswagen' class='logo'/></a>
					 <a href='http://www.suzuki-forums.com/'><img src='slike/logosuzuki.jpg' alt='volkswagen' class='logo'/></a>
					 <a href='http://www.hondaclub.rs/forum/'><img src='slike/logohonda.jpg' alt='volkswagen' class='logo'/></a>
					 <a href='http://www.volvoklubsrbija.rs/'><img src='slike/logovolvo.jpg' alt='volkswagen' class='logo'/></a>
					 <a href='http://www.6speedonline.com/forums/aston-martin-39/'><img src='slike/logoaston.jpg' alt='volkswagen' class='logo'/></a>
					 <a href='http://www.6speedonline.com/forums/aston-martin-39/'><img src='slike/logochr.jpg' alt='volkswagen' class='logo'/></a>
					 <a href='http://www.lamborghini-talk.com/'><img src='slike/logolam.jpg' alt='volkswagen' class='logo'/></a>
					 <a href='http://www.peugeotcafe.com/'><img src='slike/logopezo.jpg' alt='volkswagen' class='logo'/></a>
					 <a href='http://www.mercedesklub.rs/'><img src='slike/logomer.jpg' alt='volkswagen' class='logo'/></a>
				</div>
			</div>
		";
		}
?>